### ISSUE TITLE
missing infer_network function

### ISSUE THREAD

**Issue by developer239** [AlexisTM/FlappyNet#2]
Could you please help with writing this function? What am I missing here? I don't see neataptic being used anywhere... :/

**Comment by AlexisTM** [comment]
The function is simply not implemented as this was coded in one evening to show an example of how to create a Neural network playing X game, explaining we need to create the game before thinking artificial intelligence.

**Comment by developer239** [comment]
I am trying to get together some simple neataptic / synaptic dynamic NEAT example. This is how far I got:

https://github.com/developer239/neural-network-playground/tree/master/neatXOR

This is original code:
https://github.com/ssusnic/Machine-Learning-Flappy-Bird

It uses synaptic though. Not neataptic. And my XOR function does not work properly for some reason. I returns values close to 0 or 1 but not at the right time.

**Comment by developer239** [comment]
@AlexisTM Thanks for the help. :) If you want inspiration I found working example here: https://github.com/ssusnic/Machine-Learning-Flappy-Bird. And I got together simple `neataptic` NEAT XOR example here: https://github.com/developer239/neural-network-playground/tree/master/neatXOR

**Comment by AlexisTM** [comment]
I'll, whenever I get some free time. :D
